return {
  version = "0.1.0",
  api_version = 1,
  launchers = {
    { source = "launchers/ralf.lua", target = "/ralf.lua" },
    { source = "launchers/RalfieOS.lua", target = "/RalfieOS.lua" },
    { source = "launchers/dashboard_demo.lua", target = "/dashboard-demo.lua" },
    { source = "launchers/mining_command.lua", target = "/ralfie-mining-command.lua" },
  },
  files = {
    "core/result.lua",
    "core/module_loader.lua",
    "lib/tablex.lua",
    "lib/paths.lua",
    "lib/serialization.lua",
    "lib/fsx.lua",
    "adapters/turtle.lua",
    "bootstrap/installer.lua",
    "bootstrap/application_loader.lua",
    "bootstrap/init.lua",
    "services/platform/configuration.lua",
    "services/platform/logging.lua",
    "services/platform/updating.lua",
    "services/platform/remote_update.lua",
    "services/platform/jobs.lua",
    "services/platform/mining_protocol.lua",
    "services/platform/mining_status.lua",
    "services/platform/mining_network.lua",
    "services/operations/navigation.lua",
    "services/operations/tunnel_pattern.lua",
    "services/operations/world.lua",
    "services/operations/inventory.lua",
    "services/operations/fuel.lua",
    "services/operations/storage.lua",
    "services/operations/ore.lua",
    "services/operations/unloading.lua",
    "services/operations/fluid.lua",
    "interfaces/terminal/ui.lua",
    "interfaces/terminal/menu.lua",
    "interfaces/terminal/miner_dashboard.lua",
    "pocket/fleet.lua",
    "pocket/network.lua",
    "pocket/ui.lua",
    "pocket/main.lua",
    "apps/miner/manifest.lua",
    "apps/miner/miner.lua",
    "apps/miner/miner_5x5.lua",
    "start.lua",
    "update.lua",
    "miner.lua",
    "miner_5x5.lua",
    "ralfie.lua",
    "dashboard_demo.lua",
    "launchers/ralf.lua",
    "launchers/RalfieOS.lua",
    "launchers/dashboard_demo.lua",
    "launchers/mining_command.lua",
    "manifest.lua",
  },
}
